[project]
name = "domain-generator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "openai>=1.79.0",
    "python-dotenv>=1.1.0",
    "python-whois>=0.9.5",
]
